version: '3.9'
services:
  db:
    image: postgres:15
    container_name: my_postgres
    restart: always
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: devdb
    ports:
      - "5001:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  backend:
    build: ./server
    container_name: my_backend_app
    working_dir: /app
    ports:
      - "5000:5000"
    volumes:
      - ./server:/app
      - /app/node_modules
    env_file:
      - .env.development
    depends_on:
      - db
    command: npm run dev

volumes:
  postgres-data: